### ISSUE TITLE
Python 3 compatible?

### ISSUE THREAD

**Issue by PeterQuinn925** [gjr80/weewx_utilities#7]
I've been running this on my real hardware for a while now. It's great. 

I have a VM running with Python 3 and I'm getting the error
**** Reason: '>' not supported between instances of 'NoneType' and 'float'

It happens when executing my customized skin and does not happen when I comment out the line:
#for $day in $this_span.periods

Is there a Python 3 version of this utility? I can attempt to debug this, but I thought I'd ask before trying to hard. Any clues on what's being set to NoneType?

**Comment by gjr80** [comment]
There is no python3 version of the code as such as the code is already python2/3 compliant. Judging from the error message you posted what you are seeing is the different handling of `None` when used with `>` and `<` under python3. Under python2 you could use `None` in an expression with `<` or `>` and the expression would evaluate without error, but under python3 a `TypeError` is raised. For example, under python2:
```
>>> None > 3
False
```
but under python3:
```
>>> None > 3
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
In this case the line that is generating the error is very easy to track down as there is only one instance of `>` in an expression in `this.py`:
```
        if year_ts < start_ts or year_ts > stop_ts:
````
So it would appear that for some reason `year_ts` is `None`. At the moment I am struggling to see how that can occur.

Could you post the entire error trace from the log. Could you also give me some indication of the earliest and latest timestamps in your archive.

**Comment by PeterQuinn925** [comment]
Sorry, I got sidetracked with work and family, but I'm back at building a python 3 replacement for my weather station.

I originally had an empty database and then whatever was in there was generated by the simulator. It had only hours of data. I've since rebuilt skin piece by piece to make sure this.py was really the source of the problem. I also added my historical database to see if having no data was a problem. 

I've confirmed that the line in my template:
#for $day in $this_span.periods
is causing the problem and it's not something else that I customized. The log contains:


Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'IndentationError'>'
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Standard/index.html.tmpl
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: **** Reason: expected an indented block (cheetah__etc_weewx_skins_Standard_index_html_tmpl_1605393317_8811543_16675.py, line 1436)
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 827, in compile
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****      parseError = genParserErrorFromPythonException(
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 2045, in genParserErrorFromPythonException
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****      reader = SourceReader(source, filename=filename)
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/SourceReader.py", line 19, in __init__
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****      self._srcLen = len(src)
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****  TypeError: object of type 'NoneType' has no len()
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****  During handling of the above exception, another exception occurred:
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 315, in generate
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****      compiled_template = Cheetah.Template.Template(
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1337, in __init__
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****      self._compile(source, file, compilerSettings=compilerSettings)
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1634, in _compile
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****      templateClass = self.compile(source, file,
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 832, in compile
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****      raise e
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 823, in compile
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****      co = compile(generatedModuleCode, __file__, 'exec')
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Standard_index_html_tmpl_1605393317_8811543_16675.py", line 1436
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****      write('''                </td>
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****      ^
Nov 14 14:35:17 raspi3 weewx[5656] ERROR weewx.cheetahgenerator: ****  IndentationError: expected an indented block
Nov 14 14:35:18 raspi3 weewx[5656] INFO weewx.cheetahgenerator: Generated 13 files for report StandardReport in 2.62 seconds
Nov 14 14:35:18 raspi3 weewx[5656] DEBUG weewx.manager: Daily summary version is 2

**Comment by PeterQuinn925** [comment]
Well, after a bunch of fumbling around, I found the problem. It's not in the SLE it's check that I am doing to the results to skip the current year. I love working on Weewx, but sometimes the lack of good error reporting in the Cheetah stuff drives me crazy.

**Comment by PeterQuinn925** [comment]
I found the problem, by the way, <> doesn't work for "not equal" anymore, at least in this context. I tried to confirm the original error was caused by an nearly empty database, but it doesn't happen anymore with the correct syntax. I suspect I had some other issue that I inadvertently fixed in the process of debugging.
Thanks for your help and this really nice extension.
